### ISSUE TITLE
What's in the 0.2.0-alpha2 release?

### ISSUE THREAD

**Issue by adamretter** [lacuna/bifurcan#26]
Hi @ztellman I see that `0.2.0-alpha2` appeared on Maven Central.

Unfortunately I don't see any Git tag or release on GitHub. I was wondering if you might be able to tell me what has changed since `0.2.0-alpha1` and if there was any resolution to our open issue https://github.com/lacuna/bifurcan/issues/23 . Thanks :-)

Was there expected to be API changes? https://travis-ci.com/github/eXist-db/exist/jobs/321004943#L304

**Comment by ztellman** [comment]
Hi Adam,

Sorry for the slow response on your issues.  Your bug is resolved in the latest release (which is now tagged), and the only altered API is changing `indexOf` to return an `OptionalInt` (which is now reflected in the `CHANGELOG`).  Please let me know if you have any other issues upgrading to the latest.

**Comment by ztellman** [comment]
Oh, I also removed the `Map.from(Iterable ...)` constructor because it could create some ambiguity wrt `Map.from(IMap ...)` and `Map.from(IList ...)`.  If you add `.iterator()` to the line which is complaining in your CI, it should work fine.  Sorry that bit you.

**Comment by adamretter** [comment]
No worries about the delay, thanks for sharing your software with us :-)

**Comment by adamretter** [comment]
@ztellman Just thought I would mention that I also noticed that the Constructor for Map now takes a `ToLongFunction` instead of a `ToIntFunction` for its hash function.
