### ISSUE TITLE
timing in clojure gives slower results than clojure's persistent datastructures on inserts

### ISSUE THREAD

**Issue by hoebat** [lacuna/bifurcan#30]
I'm doing just a simple benchmark test and am finding that the standard implementation in clojure (vec) is faster than List and LinearList on inserts

```
[(h/bench-ns {}
     (dotimes [i 4]
       (let [^LinearList v (LinearList.)]
         (dotimes [i 1000000]
           (.addFirst ^LinearList v (Object.)))
         (.size v))))
   
   (h/bench-ns {}
     (dotimes [i 4])
     (reduce (fn [v i]
               (.addFirst ^List v (Object.)))
               (List.)
               (range 1000000)))
   
   (h/bench-ns {}
     (dotimes [i 4])
       (reduce (fn [v i]
                 (conj v (Object.)))
               []
               (range 1000000)))]

  [85886785
   43148048
   36295950]

  [86910871
   48210347
   37343646]
```
  
this is quite rough but I'm running it a couple of times and it consistently shows the same results. Is there a way to speed it up?

**Comment by ztellman** [comment]
A few points:

* It looks like you're not actually running the second and third benchmarks four times (you've closed off the `dotimes` before the `reduce`)
* `addLast` would be a more apples-to-apples comparison with `conj`
* using the same value for the element rather than allocating a new `(Object.)` each time will reduce the overhead and noise
* I'm not sure if you're meaning to avoid linear Bifurcan lists and transient Clojure vectors, but those would be the more idiomatic versions to use

**Comment by hoebat** [comment]
omg. I can't believe I did that - it was right at the end of testing at the repl. I added the `doseq` s because I wasn't seeing significant performance improvements over the standard clojure vec (which does really well). 

I'm working on some queuing applications and have found that that it's very easier to get things wrong in when things are mutable so I'm focusing on performance of immutable characteristics first before optimising.

Using transients gives about a 20% performance benefit - which is good but the code doesn't look as good so I'm a bit wary of using it.

I wanted to get a feel of the relative performance of the data structures, especially as the Bifurcan List acts as an Immutable Deque.  The eyeball testing show that List is still about 2x slower than clojure Vec on inserts. Is that comparison somewhat correct?

```
 10854274 - Linear addFirst
 20222802 - Linear addLast
 32439823 - List addFirst
 16505684 - Vector conj
```

**Comment by ztellman** [comment]
I don't really know what `h/bench-ns` is, so I can't speak to the results here.  I rely on Criterium for the benchmarks, which has provided reliable results for me in the past.  If I run benchmarks for 1k element lists, here's what I get:

```
user=> (ns bifurcan.benchmark-test)
nil
bifurcan.benchmark-test=> (use 'bifurcan.benchmark-test :reload-all)
nil

bifurcan.benchmark-test=> (c/quick-bench (construct-list (LinearList.) (into-array (repeat 1e3 (Object.)))))
Evaluation count : 12702 in 6 samples of 2117 calls.
             Execution time mean : 53.547058 µs
    Execution time std-deviation : 89.796311 ns
   Execution time lower quantile : 53.419115 µs ( 2.5%)
   Execution time upper quantile : 53.648191 µs (97.5%)
                   Overhead used : 12.402852 ns
nil

bifurcan.benchmark-test=> (c/quick-bench (construct-list (List.) (into-array (repeat 1e3 (Object.)))))
Evaluation count : 11508 in 6 samples of 1918 calls.
             Execution time mean : 59.032635 µs
    Execution time std-deviation : 149.703212 ns
   Execution time lower quantile : 58.764581 µs ( 2.5%)
   Execution time upper quantile : 59.165847 µs (97.5%)
                   Overhead used : 12.402852 ns

Found 1 outliers in 6 samples (16.6667 %)
	low-severe	 1 (16.6667 %)
 Variance from outliers : 13.8889 % Variance is moderately inflated by outliers
nil

bifurcan.benchmark-test=> (c/quick-bench (construct-clojure-vector [] (into-array (repeat 1e3 (Object.)))))
Evaluation count : 10632 in 6 samples of 1772 calls.
             Execution time mean : 61.011580 µs
    Execution time std-deviation : 179.750205 ns
   Execution time lower quantile : 60.762085 µs ( 2.5%)
   Execution time upper quantile : 61.214567 µs (97.5%)
                   Overhead used : 12.402852 ns
nil
```

I'll note that some of your performance issues may be related to testing 1M element lists, where for instance the `LinearList`'s copy-to-grow behavior probably isn't optimal compared to the tree-based structures.  If you actually plan to have millions of elements in-memory, go for it, but otherwise you should be benchmarking representative collection sizes using a proper benchmark harness such as Criterium.

**Comment by hoebat** [comment]
That makes a lot of sense. Thanks.

`bench-ns` is pretty simple - it just does a `System/gc` call and uses https://github.com/BrunoBonacci/mulog/blob/0.4.0/mulog-core/java/com/brunobonacci/mulog/core/NanoClock.java. for timing - it generally works pretty well but it relies on manually warming up the jit. 

From additional eyeball tests, It seems that the Bifurcan List perform well in the 100-1k range and then drops off a bit after that.
