### ISSUE TITLE
Confusion over when to use linear/forked

### ISSUE THREAD

**Issue by adamretter** [lacuna/bifurcan#35]
I am a little perplexed over when it is appropriate to call fork or linear.

I have called `map2.forked` before I then call `map2.linear` to create `map3`, however I see changes made to my `map3` reflected in my `map2`. I had thought that `forked` would mean that changes to `map3` don't affect `map2`.

It may be that I have misunderstood the docs and this isn't a bug after all. Some guidance would be appreciated please...

```java
    @Test
    public void bifurcanImmutableRemoveThenRemove() {

        /*
          1. Create the initial map1: `map { 1: true(), 2: true() }`
         */
        IMap<Integer, Boolean> map1 = new LinearMap<>();
        map1.put(1, true);
        map1.put(2, true);
        map1 = map1.forked();  // make the map immutable
        checkMapIsForked(map1);

        /*
          2. Create map2 and remove the entry with key `2`
         */
        IMap<Integer, Boolean> map2 = map1.linear();  // create a transient map for modifications
        map2 = map2.remove(2);
        map2 = map2.forked();  // make the map immutable
        checkMapIsForked(map2);

        /*
          3. Check the entries in map2 with key `1` and `2`
         */
        final Boolean expected1 = map2.get(1, null);
        assertTrue(expected1);
        final Boolean expected2 = map2.get(2, null);
        assertNull(expected2);

        /*
         4. Create map3 and remove the entry in the with key `1`
         */
        IMap<Integer, Boolean> map3 = map2.linear();  // create a transient map for modifications
        map3 = map3.remove(1);
        map3 = map3.forked();  // make the map immutable
        checkMapIsForked(map3);

        /*
         I expect map2.get(1, null) to return true
        */
        assertEquals(expected1, map2.get(1, null));

        /*
         I expect map3.get(1, null) to return null
         */
        assertNotEquals(expected1, map3.get(1, null));
    }
```

**Comment by line-o** [comment]
As I understand it 
```java
IMap<Integer, Boolean> map1 = new LinearMap<>();
map1.put(1, true);
```
is immutable as such.
So the below would be the way to mutate a copy/fork: 
```java
IMap<Integer, Boolean> map2 = map1.forked();  // create a forked map for modifications
map2 = map2.remove(1);
// doesn't do anything since the map is already forked
// or creates a second forked map
map2 = map2.forked();  
```

**Comment by adamretter** [comment]
@line-o The documentation in the [README.md](https://github.com/lacuna/bifurcan/#collections) states:

> LinearMap is a mutable hash-map

**Comment by line-o** [comment]
Yeah my comment from above is misleading. Because LinearMap is mutable it needs to be forked before it is mutated as a fork.

**Comment by ztellman** [comment]
EDIT: this was in response to a misreading of the original code, apologies

**Comment by ztellman** [comment]
This was an extremely indirect result of `IntSet.isLinear` always returning false due to it not being properly overridden.  I've confirmed that your example now exhibits the correct behavior.  Thanks for catching this, I need to give some thought as to properly expose these sorts of issues in my property-based testing.

I'll update the issue once this fix is in a released version.

**Comment by ztellman** [comment]
I've released `0.2.0-alpha6`

**Comment by line-o** [comment]
@ztellman for me to understand this better:

If I create a map I do not have to call `forked()` as long as _before_ a mutation (as in a mutation in my map implementation) first calls `forked()` or `cloned()`.
Is the above statement correct or would I _have to_ call forked as a way of committing a specific map?

**Comment by ztellman** [comment]
There is an unenforced assumption that once you call forked, you cease to interact with the collection that was forked.

**Comment by line-o** [comment]
So it would be more inline with your idea to call clone() on a map once it is exposed?

We use it as the implementation of immutable maps in a functional programming language where a mutating operation will always operate on a copy.

**Comment by ztellman** [comment]
While the `clone` methods of the `Linear*` will create an actual separate block of memory representing the same collection, the same isn't true for their immutable cousins (on reflection, calling `clone` on those should probably throw an exception rather than return the same collection).  

I'm not sure I understand how you're using the collections, but the default usage should be all immutable collections all the time.  If you have a local window in which you're making a bunch of changes, you can make them temporarily linear.  If you're never sharing the collection, using the `Linear*` collections may be appropriate.  The fact that you *can* call `LinearMap.forked()` doesn't mean it's the right thing to do in most cases.  If you can provide more details, I might be able to give more specific advice.

**Comment by line-o** [comment]
In that functional language, Xquery, any map is immutable.
So any operation `f : map -> map` _must_ return a new map.
How would you implement that using your implementation?
The current implementation you can derive from @adamretter code examples, where each step 1.,2.,3.,... is a statement in Xquery.

**Comment by adamretter** [comment]
@ztellman Thanks for being so responsive as always Zach, it's much appreciated. Also thanks for the prompt fix, I will upgrade our project to use it.

@line-o I believe that the code as I had it before is still correct, and that this fix resolves the issue we saw.
